name: Haskell

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Haskell (GHC and Stack)
        uses: haskell/actions/setup@v2
        with:
          stack-version: 'latest'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build
        run: stack build

      - name: Test Part 1
        run: stack test --ta "-p Part1"

      - name: Test Part 2
        run: stack test --ta "-p Part2"

      - name: Test Part 3
        run: stack test --ta "-p Part3"

      - name: Test Part 4
        run: stack test --ta "-p Part4"

      - name: Test Part 5
        run: stack test --ta "-p Part5"

      - name: Test Part 6
        run: stack test --ta "-p Part6"
